### PR TITLE
Give GCP access to Sean

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://github.com/2i2c-org/team-compass/issues/76
     
Requires https://github.com/2i2c-org/org-ops/pull/1

Terraform plan is:

```
─$ terraform plan -var-file projects.tfvars
Acquiring state lock. This may take a few moments...
google_project.fully_managed_project["two-eye-two-see"]: Refreshing state... [id=projects/two-eye-two-see]
google_project_iam_binding.project_owners["two-eye-two-see"]: Refreshing state... [id=two-eye-two-see/roles/owner]
google_storage_bucket.managed_terraform_state: Refreshing state... [id=two-eye-two-see-org-terraform-state]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # google_project_iam_binding.project_owners["cb-1003-1696"] will be created
  + resource "google_project_iam_binding" "project_owners" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + members = [
          + "user:choldgraf@2i2c.org",
          + "user:damianavila@2i2c.org",
          + "user:erik@2i2c.org",
          + "user:georgianaelena@2i2c.org",
          + "user:sean.smorris@berkeley.edu",
          + "user:yuvipanda@2i2c.org",
        ]
      + project = "cb-1003-1696"
      + role    = "roles/owner"
    }

  # google_project_iam_binding.project_owners["two-eye-two-see"] will be updated in-place
  ~ resource "google_project_iam_binding" "project_owners" {
        id      = "two-eye-two-see/roles/owner"
      ~ members = [
          + "user:sean.smorris@berkeley.edu",
            # (5 unchanged elements hidden)
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

Releasing state lock. This may take a few moments...
```

Note that this includes the changes for #1

### CODE REVIEW

**Comment by damianavila** [comment]
Not sure why not, I can not see the settings tab here, so I guess is a permission issue that maybe @choldgraf could fix?

**Review by damianavila — APPROVED** [review]
LGTM, one-line change on the top of #1.

**Comment by choldgraf** [comment]
I've added the tech team to this repository as a maintainer. We need to add groups or people explicitly in order to be able to request reviews and such

**Comment by choldgraf** [comment]
Is there anything blocking this from merge? I think we need less "approving" and more "merging" for these more non-controversial things :-)

**Comment by damianavila** [comment]
> Is there anything blocking this from merge? I think we need less "approving" and more "merging" for these more non-controversial things :-)

In this case, I disagree 😉 ... well, actually, I like the model "I submit, you review and approve, I merge", but that's a personal choice and I am happy to work with other workflows.
But coming back to this specific case, I think there is some coordination needed for the deployment.
Check step 4 here: https://pilot-hubs.2i2c.org/en/latest/howto/operate/setup-new-project.html#client-organization-provides-billing-account

**Comment by choldgraf** [comment]
Sounds good 🙂 i just wanted to make sure we weren't all waiting for the other person to press the green button 🙃

**Comment by yuvipanda** [comment]
For the same reason as https://github.com/2i2c-org/org-ops/pull/1#issuecomment-831348657, this also does not work, since @sean-morris doesn't have a 2i2c.org account.

```

google_project_iam_binding.project_owners["two-eye-two-see"]: Modifying... [id=two-eye-two-see/roles/owner]

Error: Request "Set IAM Binding for role \"roles/owner\" on \"project \\\"two-eye-two-see\\\"\"" returned error: Error applying IAM policy for project "two-eye-two-see": Error setting IAM policy for project "two-eye-two-see": googleapi: Error 400: Request contains an invalid argument., badRequest

  on main.tf line 26, in resource "google_project_iam_binding" "project_owners":
  26: resource "google_project_iam_binding" "project_owners" {


Releasing state lock. This may take a few moments...
```

**Comment by yuvipanda** [comment]
I've already given access manually to the projects. I should document that though.

**Comment by choldgraf** [comment]
@yuvipanda so we cannot automatically give access to projects for people that don't have a 2i2c.org account, yes?

And just to confirm, we can't do this with an alias account like `sre@2i2c.org`?

**Comment by yuvipanda** [comment]
This repo should be abandoned.

**Pull request closed without merging**
